# Generated by Django 6.0.6 on 2026-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.IntegerField(db_column='case_id', primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('user_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('loss_value', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'case_submissions',
                'ordering': ['-submitted_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.IntegerField(db_column='evidence_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name', max_length=100)),
                ('evidence_type', models.CharField(db_column='evidence_type', max_length=50)),
                ('found_at', models.CharField(db_column='found_at', max_length=100)),
                ('details', models.TextField(blank=True, db_column='details', null=True)),
            ],
            options={
                'db_table': 'evidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_key_evidence', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'solution_evidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionSuspect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_guilty', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'solution_suspects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_selected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'submission_evidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionSuspect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_accused', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'submission_suspects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.IntegerField(db_column='suspect_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('motive', models.TextField(blank=True, null=True)),
                ('alibi', models.TextField(blank=True, null=True)),
                ('alibi_status', models.CharField(blank=True, max_length=50, null=True)),
                ('suspect_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'suspects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('rank', models.CharField(default='Rookie', max_length=100)),
                ('cases_solved', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
