# Generated by Django 6.0.7 on 2026-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='age',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='status',
        ),
        migrations.AddField(
            model_name='suspect',
            name='alibi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='alibi_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='motive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='suspect_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
